In [12]:
import numpy as np
list=[['1',2,'@'],
      [5,'s',99]
     ]
print(list)
np.array(list)

[['1', 2, '@'], [5, 's', 99]]


array([['1', '2', '@'],
       ['5', 's', '99']], dtype='<U2')

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones(3)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.linspace(1,10,21)

array([ 1.  ,  1.45,  1.9 ,  2.35,  2.8 ,  3.25,  3.7 ,  4.15,  4.6 ,
        5.05,  5.5 ,  5.95,  6.4 ,  6.85,  7.3 ,  7.75,  8.2 ,  8.65,
        9.1 ,  9.55, 10.  ])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.random.rand(10)

array([0.97475312, 0.10194277, 0.31418989, 0.16506792, 0.09926671,
       0.78283029, 0.27699394, 0.93984289, 0.50584188, 0.55721644])

In [47]:
np.random.randn(10)

array([ 0.38255693, -1.52269242, -0.44963388, -0.26766419, -0.52728147,
       -0.25242108, -0.19403458, -1.10199151,  1.59441431,  1.01382055])

In [53]:
np.random.randint(10,100,5)

array([95, 44, 68, 98, 81])

In [59]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [60]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [61]:
arr = np.arange(25)

In [62]:
ranarr = np.random.randint(0,50,10)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
arr.shape

(25,)

In [66]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
arr.reshape(3,6)

ValueError: cannot reshape array of size 25 into shape (3,6)

In [72]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [71]:
ranarr.max()

43

In [73]:
ranarr.argmax()

7

In [74]:
ranarr.argmin()

5

In [75]:
ranarr.dtype

dtype('int32')

In [77]:
myarr = np.random.rand(4)
myarr

array([0.00706631, 0.02306243, 0.52477466, 0.39986097])

In [78]:
myarr.dtype

dtype('float64')

In [83]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
slice_arr = arr[:5]  # referance variable or broadcasting in array
slice_arr

array([0, 1, 2, 3, 4])

In [87]:
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100])

In [88]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [1]:
#to avoid Broadcasting is .copy function.
arrCopy = arr.copy()
arrCopy

NameError: name 'arr' is not defined